
const TooltipInfoMap = {
    'hello-world': 'hello-world is a simple program used to introduce syntax, environment setup, and output functionality',
    'gitbash': 'GitBash is a terminal emulator for Git on Windows, facilitating version control and command-line operations',
    'sourcetree': 'SourceTree is a graphical Git client used for managing repositories, simplifying version control workflows visually',
    'directx': 'DirectX is an API framework facilitating advanced 3D graphics rendering for Windows, Xbox and Linux',
    'vulkan': 'Vulkan is a cross-platform API framework for high-performance 3D graphics rendering',
    'data driven development': 'Data-Driven Development is an approach where functionality is based on data, iterative development, and easy modification to empower designers',
    'source control': 'Source Control is a system managing changes to code, enabling collaboration, tracking history, and ensuring versioning',
    'debugging': 'Debugging in an IDE allows developers to identify and fix software issues efficiently with integrated tools',
    'perforce': 'Perforce is a version control system facilitating collaborative software development, particularly in game development environments',
    'repository': 'A repository, or repo, is a central location/database where all project files and their version history are stored',
    'git': 'Git is an open source control system for tracking changes in source code during software development',
    'gitlab': 'GitLab unlike GitHub is open-source, it is a web-based source control system',
    'github': 'A web-based platform for version control using Git, facilitating collaboration, code sharing, and project management among software developers',
    'open-source': 'Open-source software is publicly accessible code that can be freely inspected, modified, and distributed',
    'ide' : 'IDE stands for Integrated Development Environment, they provide developers with tools for writing, debugging, and testing code',
    'code completion' : 'Code Completion is a feature in IDEs that automatically suggests and completes code, variable names, methods, and other elements as you type',
    'c++': 'An advanced programming language, known for its high performance and low-level control, making it ideal performance-critical applications',
    'c#': 'A modern programming language developed by Microsoft, known for its strong support for object-oriented programming and its rich set of features',
    'java': 'A high-level, object-oriented programming language. Known for its simplicity, platform independence, and robustness',
    'api': 'Application Programming Interface, which provides a set of pre-defined functions, classes, and protocols. Streamlining the development process and promoting code reuse',
    'jvm' : 'Java Virtual Machine, is an abstract computing machine that enables Java code to be executed regardless of platform',
    'console' : 'A text-based interface for user-computer interaction, enabling text input and output, often used for program execution, system monitoring, and debugging',
    'program arguments' : 'Flags or values that you can pass into an application. Can be viewed as inputs that can enable/disable certain features or functionality of an application',
    'environment variables' : 'Variables that are part of the operating systems environment. They store information such as paths to important directories, system configurations, or user preferences',
    'variable' : 'A symbolic name that represents a stored value in code',
    'class' : 'A container defining variables and functionality to serve a specific purpose in an application or feature',
    'abstraction' : 'The process of simplifying complex systems by focusing on essential properties while hiding unnecessary details',
    'inheritance' : 'A feature of object-oriented programming where a new class inherits properties and behaviors (methods) from a given class',
    'polymorphism' : 'A feature of object-oriented programming where different classes can be treated interchangeably, allowing flexible method behaviors that can be overridden in a hierarchical class structure',
    'signed' : 'Signed data types reserve one bit to represent the sign of the value, allowing for both positive and negative values',
    'unsigned' : 'Unsigned data types use all bits to represent the only positive values',
    'operators' : 'Operators are symbols that perform operations on operands. They can be arithmetic (like +, -, *, /), relational (like ==, !=, >, <), logical (like &&, ||), and more',
    'scope' : 'Scopes determine where a variable or a function can be accessed. There are two main types of scope: local and global',
    'class instance' : 'A single occurrence of an object, created from a class. It has its own properties and methods',
    'refactor' : 'Process of improving code structure without altering its functionality for better readability and maintainability',
    'operand' : 'An operand in programming is a data item that operators perform operations on',
    'operands' : 'Operands in programming are a data items that operators perform operations on',
    'arithmetic' : 'Refers to dealing with numerical computation using math, such as addition, subtraction, multiplication, and division',

};

export default TooltipInfoMap;